### PR TITLE
Associate overlay with specific slideReveal element to allow multiple overlays

### PR DESCRIPTION
**Pull request by timcheadle**
I'm using `slideReveal({overlay: true})` on multiple elements, which results in multiple `.slide-reveal-overlay` divs. This is fine, except their background colors combine for a much darker overlay than users likely intend because all overlays are shown at once.

This simple fix just associates an overlay with it's specific slideReveal element so only one overlay is shown at a time.

### CODE REVIEW

**Comment by timcheadle** [comment]
I've updated the PR description to reflect the actual fix here.

**Comment by nnattawat** [comment]
Thanks @timcheadle for spotting that. Your fix looks good, however, I am thinking whether it will be better just to have one overlay element used across all panels as most of the cases, they will all be the same style overlay.

**Comment by timcheadle** [comment]
Agreed; that was my original solution until I realized I'd have to make more structural changes to identify the correct panel to open when someone clicks the overlay.

**Comment by nnattawat** [comment]
I have decided to merge your changes but I attach the overlay to the model instead of data attribute. You can have a look [here](https://github.com/nnattawat/slideReveal/commit/ef0f1315def764d8f5d81d04e21e25c3367002e4). Thanks for your PR! 😄

**Pull request merged**
